### ISSUE TITLE
Odkazy na forum.mozilla.cz

### ISSUE THREAD

**Issue by zelitomas** [MozillaCZ/ukoly#11]
Po přesunu SUMA na Lithium přestaly být funkční odkazy "Položit dotaz k..." z úvodní strany forum.mozilla.cz

**Comment by MikkCZ** [comment]
Bude potřeba opravit v https://github.com/MozillaCZ/prosilver_mozillacz až bude fixnutý https://bugzilla.mozilla.org/show_bug.cgi?id=1337675
