### ISSUE TITLE
Zorganizovat první meetup

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#12]
První meetup by měl být bez veřejnosti, jen pro organizační věci. Retrospektiva a trochu plány. Následně udělat meetupy pravidelné včetně veřejnosti. :)

**Comment by zelitomas** [comment]
E-mail rozeslán, uvidíme, jaká bude odezva...

**Comment by MikkCZ** [comment]
FYI pro veřejné meetupy jsem vyrobil "placeholder" na https://www.meetup.com/mozilla-prague/. Uvidíme, jak rychle a kolik se tam přidá lidí. Zatím tam vede jediný odkaz z webu Mozilla.cz (odkazy vpravo na sociální sítě). Nějakou větší propagaci budu dělat tak do 14 dnů, dřív úplně ne.

**Comment by MikkCZ** [comment]
@zelitomas Jak to vypadá?

**Comment by MikkCZ** [comment]
Interní setkání nedopadlo, takže jdeme rovnou na veřejná. https://www.meetup.com/mozilla-prague/
