### ISSUE TITLE
Začít pravidelné videokonference

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#17]
Na Slacku jsme se docela shodli, že by bylo fajn mít pravidelné videokonference. NA to budeme potřebovat hlavně vhodnou službu, která nám nejlépe nabídne i záznam, který pak můžeme nahrát na AirMo.
- [ ] vybrat nejvhodnější službu (Vidyo, appear.in, zoom.us, Meetecho, Gruveo, Hangouts, Skype, Jitsi, něco z https://get.slack.help/hc/en-us/articles/208492868-Voice-video-screen-sharing-apps, ...)
- [ ] založit repositář pro postupy a zápisy

**Comment by MikkCZ** [comment]
@zelitomas Chceš se tedy na to podívat?

**Comment by vasimi** [comment]
@MikkCZ Možností by mohlo být přejít na placený Slack. Umí až 15 lidí. Myslím, že jsi říkal něco o tom, že by nám to Mozilla mohla platit?

Edit: Sorry, když jsem zmáčknul enter, došlo mi, že vlastně budeme moct mít placený Slack zdarma jako spolek. Každopádně Slack je tedy jednou z možností, a nemuseli bychom ani zavádět další platformu.

**Comment by MikkCZ** [comment]
Vidím, že se toho už Tomáš chopil. ;)
