### ISSUE TITLE
Template pro prezentaci

### ISSUE THREAD

**Issue by zelitomas** [MozillaCZ/ukoly#30]
Template s moderním vzhledem, s převodem z markdownu do HTML a PDF.

**Comment by MikkCZ** [comment]
@zelitomas Super. V jakém je to stavu? Mohl bys do readme v [repositáři](https://github.com/MozillaCZ/moztemplate.md) popsat, jak to používat, případně vyplnit issues v tom repositáři, co je ještě potřeba nebo nefunguje dokonale?
