### ISSUE TITLE
WP Super Cache nečistí staré soubory

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#31]
Z nějakého důvodu přestalo fungovat mazání starých souborů z keše WP Super Cache. Po vydání naplánovaného článku se tak nikde neobjeví, jenom na Twitteru a přes přímý odkaz. Návštěvníci ale vidí zakešovanou verzi domovské stránky i feedu.

**Comment by MikkCZ** [comment]
Trochu jsem upravil nastavení. Uvidíme, jestli to pomůže. Plugin teď navíc doporučuje variantu kešování pomocí PHP místo mod_rewrite, což můžeme použít, pokud by změna nastavení nepomohla.

**Comment by jrychly** [comment]
Dneska mně a @MekliCZ vyšly dva články a nebyl s tím problém, takže je to podle mě opravené, pokud do toho někdo nějak nehrabal.

**Comment by MikkCZ** [comment]
Díky. Ani jsem to nevěděl. Je potřeba to kontrolovat nepřihlášený - pro přihlášené uživatele se keš nepoužívá. Ale kouknul jsem teď na to a vypadá to v pohodě. Zavírám. :)
