### ISSUE TITLE
Stánek na DevConf.cz

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#4]

**Comment by MikkCZ** [comment]
Hi.

I would like to ask, if there is any space left for Mozilla.cz booth on DevConf.cz 2017? We are Czech Mozilla community. Mainly we take care about localization (Firefox, Thunderbird, addons.mozilla.org, mozilla.org, Test Pilot, everything...) and we do our best to inform about news in Firefox and Mozilla on our website and Twitter.

This year we attended LinuxDays in Prague and OpenAlt in Brno and would like to continue in the trend on DevConf.cz. The format of the booth would be most likely the same - we will have some swag (stickers, tattoos, buttons, maybe T-shirts) to give away, and we will be present on the booth to answer questions. I expect on DevConf.cz to mostly answer questions or talk about Firefox with all the visitors, but on LinuxDays and OpenAlt we were also helping people to solve issues, or direct them to the right support place, if we were no able to resolve the particular case personally on the place.

If you would like the booth to be organized in some particular way and format, different than I mentioned above, please let me know. We are still learning.

Cheers,
Michal Stanke

**Comment by MikkCZ** [comment]
E-mail poslán organizátorům. Snad se vejdeme.

**Comment by MikkCZ** [comment]
Ladím organizační detaily s pořadateli. @MekliCZ a @zelitomas jsou kdyžtak v kopii.

**Comment by vasimi** [comment]
@MikkCZ Už dlouhou dobu mi nic nedorazilo, jak to vypadá?

**Comment by MikkCZ** [comment]
Promiň. Stránek bude. Dostavit se máme v sedm ráno v sobotu. E-mail
přepošlu.

**Comment by MikkCZ** [comment]
Program přednášek bude v pondělí.
