### ISSUE TITLE
Mrtvy odkaz ze Zapojte se

### ISSUE THREAD

**Issue by janbrasna** [MozillaCZ/ukoly#45]
### Jak chybu zreprodukovat
1. https://www.mozilla.cz/zapojte-se/
2. posledni kapitola "Nic z toho mne nezajímá" 
3. odkaz na whatcanidoformozilla.org vede na nejaky divny vietnamsky blog o televizi//fotbalu?

### Co se stalo

Obsah co byval na whatcanidoformozilla.org uz asi neexistuje a domenu nekdo slohnul a presmeroval…

### Očekávané chování

Asi by se odkaz mel odstranit, uz na tom jen nekdo parazituje.

**Comment by JasnaPaka** [comment]
Děkujeme za upozornění. Nevhodný odkaz jsme odstranili.
