### ISSUE TITLE
Vytvořit na Mozilla.cz nějaký trénink pro učení nových přispěvatelů

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#6]
https://bugzilla.mozilla.org/show_bug.cgi?id=1235782

@MikkCZ: Něco jako One and Done. Existuje na to i WordPress plugin DaTask https://github.com/Mte90/DaTask

@MikkCZ: Chceme-li něco takového zavést, má smysl to udělat po restartu L10N.cz. Podle mne je trénink ukázková oblast na spolupráci.

**Comment by jrychly** [comment]
Co zkusit udělat nějaké úložky "drag and drop". Nějak dobře a zábavně graficky zpracované na webu. Bude to samo vyhodnocovat a když to udělají, tak si to po nich vyžádá mail nebo nás to informuje.

**Comment by MikkCZ** [comment]
Myslím, že příručka (#14) by měla stačit.

**Comment by MikkCZ** [comment]
Kdybychom to někdy chtěli oživil, můžeme asi použít https://plugins.gitbook.com/plugin/exercises, třeba i přímo v rámci dokumentaci od Mozilly, pro vytvoření nějakých interaktivních příkladů a hrátek.
