### ISSUE TITLE
Výzva na start.mozilla.cz

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/ukoly#9]
Na start.mozilla.cz by se hodila výzva alespoň k zapojení se do překladů SeaMonkey.

**Comment by zelitomas** [comment]
Ahoj, pustil jsem se do toho, ale nevím, jestli by bylo lepší umístit ten box nahoru (byl by líp vidět, ale zato by byl dost otravný), nebo spíš dolů. Co říkáš, je lepší tohle:

![snimek z 2017-02-03 01-23-42](https://cloud.githubusercontent.com/assets/3105674/22574866/ffd250f4-e9b1-11e6-90c9-015983894549.png)

nebo toto:

![snimek z 2017-02-03 01-23-06](https://cloud.githubusercontent.com/assets/3105674/22574870/090bbba6-e9b2-11e6-936f-962e5363fe0e.png)

??

**Comment by MikkCZ** [comment]
Klidně bych to dal pod vyhledávač (druhá varianta) s možností to schovat. Dříve tak fungovala kontrola aktuální verze, viz https://github.com/MozillaCZ/start-mozilla-cz/issues/13.
